version: '3'

services:
  mysql:
    image: mariadb:10.11-jammy
    container_name: 'hoteli_db'
    environment:
      MARIADB_RANDOM_ROOT_PASSWORD: yes
      MARIADB_DATABASE: hoteli
      MARIADB_USER: hoteli
      MARIADB_PASSWORD: hoteli
    ports:
      - 3306:3306
  web:
    image: webdevops/php-apache:8.0
    container_name: 'hoteli_www'
    ports:
      - 80:80
    volumes:
      - ./www:/app:ro
